Importing NUMPY AND ITS USES

In [ ]:
!pip install numpy
import numpy as np

list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr=np.array([list1,list2,list3])
print(list1,list2,list3)

[1, 2, 3, 4, 5] [6, 7, 8, 9, 10] [11, 12, 13, 14, 15]


In [ ]:
!pip install numpy
import numpy as np

list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
A1=np.array([list1,list2,list3])
print(A1[1:,1:3])

[[ 7  8]
 [12 13]]


In [ ]:
np.arange(2,18).reshape(4,4)


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
np.random.randint(0,50,4).reshape(2,2)

array([[ 7,  1],
       [10,  0]])